services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /srv/dev-disk-by-uuid-e98d919a-9fde-4bce-a411-5b2f3be98d2a/Docker/Linkwarden/postgre:/var/lib/postgresql/data

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    restart: always
    environment:
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - /srv/dev-disk-by-uuid-e98d919a-9fde-4bce-a411-5b2f3be98d2a/Docker/Linkwarden/linkwarden_data:/data/data

volumes:
  data: